### ISSUE TITLE
Allows execution of user submitted javascript

### ISSUE THREAD

**Issue by mudrd8mz** [dredix84/moodle-filter_html5media#1]
There is a security bug in the code allowing for submitted javascript execution. On a site with the filter enabled, users can post something like

```
<a href="'onerror='alert();'src=xss.mp3"></a>
```

and the script defined in the `onerror` gets executed. See https://html5sec.org/#55 for details.

**Comment by dredix84** [comment]
Issue has been addressed with an additional check  which skips string replacement and regex also would need pass such a string as a match.
See commit below for details.
8bc7e9d982789fac52a8f5169452eb3a32941ed6
